language: python
dist: 'xenial'
sudo: true
python:
  - '3.7.0'
install: 
  - 'pip install pipenv'
  - 'pipenv install'
  - 'pip install --pre pybuilder'
script: 
  - 'cd example'
  - 'pyb clean install_dependencies publish'